
services:
  - type: web
    name: rideviz-service
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: ./
    plan: free
    region: oregon
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: PORT
        value: 3000
      - key: RUST_LOG
        value: info
      - key: MAX_FILE_SIZE_MB
        value: 25
      - key: CACHE_TTL_SECONDS
        value: 3600
      - key: VITE_POSTHOG_API_KEY
        sync: false
    healthCheckPath: /health
    autoDeploy: true
